spring:
  data:
    mongodb:
      authentication-database: ${MONGO_DB_AUTH_DATABASE:admin}
      username: ${MONGO_DB_USERNAME:root} #your container's credential
      password: ${MONGO_DB_PASSWORD:javadevs} #your container's credential
      database: ${MONGO_DB_DATABASE:user-account} #mongodb's container database name
      port: ${MONGO_DB_PORT:27017}  #container's port in which your mongodb is running
      host: ${MONGO_DB_URL:db_host}  #your image's name i.e. in my case it is mongodb


      
      
      




